### ISSUE TITLE
Peer Dependencies

### ISSUE THREAD

**Issue by gregorskii** [auniverseaway/react-dom-components#8]
Hi!

I see this package uses peer dependencies:

https://github.com/auniverseaway/react-dom-components/blob/master/package.json#L46

Are these dependencies required to be peer? Isn't the end result of this package fully compiled, does it need to require babel etc?

The issue with having these peer deps is it requires people to have the same version required in their app or have warnings.

What do you think, can these be moved to regular deps?

Thanks

**Comment by pjbrof** [comment]
It doesn't look like these are required. I think Chris removed the babel deps but I'm still seeing warnings for react. This should work for previous versions of react and react-dom pre v16.2 unless you use the fragment syntax thats in the documentation. If thats the case I'd recommend using `>= 16.2.0 < 17` so we can keep up with the latest features of react.

**Comment by auniverseaway** [comment]
@gregorskii @pjbrof @chrischrischris 

I took care of the babel peer dependencies in `1.0.4`, but there is a bigger issue with the React peer dependency that is an architectural problem in that we instantiate the React Component inside the `DOMComponent` class. This means your version really should match RDC.

It will be API-breaking, but we need to figure out how to support BYORV (Bring Your Own React Version) use cases.

**Comment by auniverseaway** [comment]
As of 2.0, all peer dependencies have been removed. @gregorskii Let me know if you have any more issues.

**Comment by gregorskii** [comment]
Awesome thank you! Will do
